global:
  scrape_interval: 15s 
  evaluation_interval: 15s
  external_labels:
    origin: 'nitroberry-production'

remote_write:
  - url: ${REMOTE_WRITE_URL}
    basic_auth:
      username: ${PROMETHEUS_USER_ID}
      password: ${PROMETHEUS_API_KEY}

scrape_configs:
  - job_name: 'nitroberry-api'
    metrics_path: '/metrics'
    static_configs:
      # Dynamically injected target
      - targets: ['${APP_TARGET}'] 
    relabel_configs:
      - target_label: 'environment'
        replacement: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']